/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fanis.koustoulas.app.estia;

import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Fanis
 */
public class UserPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel
     */
    Main m;
    DBController db = new DBController("ESTIA2","");
    public UserPanel(Main m) {
        super();
        this.m = m;
        
        initComponents();
        this.setVisible(true);
        setTableData();
        
        
        
        
    }
    
    private ArrayList listUsers(){
        
        ResultSet student = db.query(""
                + "SELECT * FROM STUDENT INNER JOIN ADDRESS ON STUDENT.ID = ADDRESS.ID "
                + "INNER JOIN GONEIS ON STUDENT.ID = GONEIS.ID " 
                + "INNER JOIN TILEFONO ON STUDENT.ID = TILEFONO.ID "
                + "INNER JOIN STOIXEIA ON STUDENT.ID = STOIXEIA.ID ");
        
        Object row[];
        ArrayList<Object> list = new ArrayList();
        try {
            while(student.next()){
                
                row = new Object[18];
                row[0] = student.getInt("ID");
                row[1] = student.getString("SNAME");
                row[2] = student.getString("SLASTNAME");
                row[3] = student.getString("SROOM");
                row[4] = student.getString("NOMOS");
                row[5] = student.getString("POLI");
                row[6] = student.getString("DIEUTHINSI");
                row[7] = student.getInt("ARITHMOS");
                row[8] = student.getString("ONOMAMITROS");
                row[9] = student.getString("ONOMAPATROS");
                row[10] = student.getString("KINITOIDIOU");
                row[11] = student.getString("KINITOPATROS");
                row[12] = student.getString("KINITOMITROS");
                row[13] = student.getString("STATHERO");
                row[14] = student.getString("ARITHMOSTAUTOTITAS");
                row[15] = student.getString("IMEROMINIAEISODOU");
                row[16] = student.getString("IMEROMINIAEKSODOU");
                row[17] = student.getString("EIDIKOTITA");
                list.add(row);
                
            }
            return list;
        } catch (Exception ex) {
            Logger.getLogger(UserPanel.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    
    private void setTableData(){
        ArrayList<Object> list = listUsers();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        for(int i = 0; i < list.size(); i++){
            model.addRow((Object[])list.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        insertBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        nameText = new javax.swing.JTextField();
        surnameText = new javax.swing.JTextField();
        roomText = new javax.swing.JTextField();
        printButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        numberText = new javax.swing.JTextField();
        mothernameText = new javax.swing.JTextField();
        fathernameText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        kinitoText = new javax.swing.JTextField();
        kinitomText = new javax.swing.JTextField();
        kinitopText = new javax.swing.JTextField();
        statheroText = new javax.swing.JTextField();
        artautoText = new javax.swing.JTextField();
        imEisText = new javax.swing.JTextField();
        eidikotitaText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        imeks = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ΟΝΟΜΑ", "ΕΠΩΝΥΜΟ", "ΔΩΜΑΤΕΙΟ", "ΝΟΜΟΣ", "ΠΟΛΗ", "ΔΙΕΥΘΥΝΣΗ", "ΑΡ.", "Ον.Μητ.", "Ον.Πατ.", "ΚΙΝΗΤΟ", "Κιν.Μητ", "Κιν.Πατ", "Σταθερο", "Αρ.Ταυ", "Ημ.Εισ.", "Ημ.Εξόδου", "Ειδικότητα"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(10).setResizable(false);
            jTable1.getColumnModel().getColumn(11).setResizable(false);
            jTable1.getColumnModel().getColumn(12).setResizable(false);
            jTable1.getColumnModel().getColumn(13).setResizable(false);
            jTable1.getColumnModel().getColumn(14).setResizable(false);
            jTable1.getColumnModel().getColumn(15).setResizable(false);
            jTable1.getColumnModel().getColumn(16).setResizable(false);
            jTable1.getColumnModel().getColumn(17).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("ΟΝΟΜΑ:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("ΕΠΩΝΥΜΟ:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("ΝΟΜΟΣ:");

        insertBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insertBtn.setText("Εισαγωγή");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setText("Ανανέωση στοιχείων");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setText("Διαγραφή");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        printButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printButton.setText("Εκτύπωση");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("ΠΟΛΗ:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("ΔΙΕΥΘΥΝΣΗ:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("ΑΡΙΘΜΟΣ:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("ΟΝΟΜΑ ΜΗΤΡΟΣ:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("ΟΝΟΜΑ ΠΑΤΡΟΣ:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("ΚΙΝΗΤΟ:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("ΚΙΝΗΤΟ ΜΗΤΡΟΣ:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("ΚΙΝΗΤΟ ΠΑΤΡΟΣ:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("ΣΤΑΘΕΡΟ ΣΠΙΤΙΟΥ:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("ΑΣΤ.ΤΑΥΤΟΤΗΤΑ:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("ΗΜ. ΕΙΣΑΓΩΓΗΣ:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("ΕΙΔΙΚΟΤΗΤΑ:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("ΔΩΜΑΤΕΙΟ:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Εισαγωγή νέου φοιτητή/επεξεργασία στοιχείων επιλεγμένου φοιτητή");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("ΗΜ. ΕΞΑΓΩΓΗΣ:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(surnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(roomText, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(stateText)
                                    .addComponent(cityText)
                                    .addComponent(addressText)
                                    .addComponent(numberText)
                                    .addComponent(mothernameText)
                                    .addComponent(fathernameText)
                                    .addComponent(kinitoText)
                                    .addComponent(kinitomText)
                                    .addComponent(kinitopText)
                                    .addComponent(statheroText)
                                    .addComponent(artautoText)
                                    .addComponent(imEisText)
                                    .addComponent(imeks)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eidikotitaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)
                        .addGap(4, 4, 4)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addressText, artautoText, cityText, eidikotitaText, fathernameText, imEisText, kinitoText, kinitomText, kinitopText, mothernameText, nameText, numberText, roomText, stateText, statheroText, surnameText});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mothernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fathernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kinitoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kinitomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kinitopText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statheroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(artautoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imEisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(printButton)
                            .addComponent(insertBtn)
                            .addComponent(deleteBtn)
                            .addComponent(updateBtn))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(imeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eidikotitaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        id = (Integer)jTable1.getModel().getValueAt(i, 0);
        TableModel model = jTable1.getModel();
        
        
        
        
        nameText.setText((String)model.getValueAt(i, 1));
        surnameText.setText((String)model.getValueAt(i, 2));
        roomText.setText((String)model.getValueAt(i, 3));
        stateText.setText((String)model.getValueAt(i, 4));
        cityText.setText((String)model.getValueAt(i, 5));
        addressText.setText((String)model.getValueAt(i, 6));
        numberText.setText(String.valueOf((int)model.getValueAt(i, 7)));
        mothernameText.setText((String)model.getValueAt(i, 8));
        fathernameText.setText((String)model.getValueAt(i, 9));
        kinitoText.setText((String)model.getValueAt(i, 10));
        kinitomText.setText((String)model.getValueAt(i, 11));
        kinitopText.setText((String)model.getValueAt(i, 12));
        statheroText.setText((String)model.getValueAt(i, 13));
        artautoText.setText((String)model.getValueAt(i, 14));
        imEisText.setText((String)model.getValueAt(i, 15));
        imeks.setText((String)model.getValueAt(i, 16));
        eidikotitaText.setText((String)model.getValueAt(i, 17));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        

        //krataei thn epomenh timh apo to teleutaio id pou eisxwrh8hke;
        if(jTable1.getModel().getRowCount() == 0){
            currentID = 0;
        }else{
            currentID = (Integer)jTable1.getModel().getValueAt(jTable1.getModel().getRowCount() - 1, 0) + 1;
        }
        if(!nameText.getText().isEmpty() && !surnameText.getText().isEmpty() && !roomText.getText().isEmpty() && !stateText.getText().isEmpty() && !cityText.getText().isEmpty() && !addressText.getText().isEmpty() && !numberText.getText().isEmpty() && !kinitoText.getText().isEmpty() && !kinitomText.getText().isEmpty() && !kinitopText.getText().isEmpty() && !statheroText.getText().isEmpty() && !fathernameText.getText().isEmpty() && !mothernameText.getText().isEmpty() && !artautoText.getText().isEmpty() && !imEisText.getText().isEmpty() && !eidikotitaText.getText().isEmpty()){
            if(roomText.getText().matches("[0-9]*") && numberText.getText().matches("[0-9]*")){
                db.insert("INSERT INTO STUDENT(ID,SNAME,SLASTNAME,SROOM) VALUES("+currentID+",'"+nameText.getText()+"','"+surnameText.getText()+"',"+Integer.valueOf(roomText.getText())+")");            
                db.insert("INSERT INTO ADDRESS(ID,NOMOS,POLI,DIEUTHINSI,ARITHMOS) VALUES("+currentID+",'"+stateText.getText()+"','"+cityText.getText()+"','"+addressText.getText()+"',"+Integer.valueOf(numberText.getText())+")");            
                db.insert("INSERT INTO GONEIS(ID,ONOMAMITROS,ONOMAPATROS) VALUES("+currentID+",'"+mothernameText.getText()+"','"+fathernameText.getText()+"')");
                db.insert("INSERT INTO TILEFONO(ID,KINITOIDIOU,KINITOPATROS,KINITOMITROS,STATHERO) VALUES("+currentID+",'"+kinitoText.getText()+"','"+kinitomText.getText()+"','"+kinitopText.getText()+"','"+statheroText.getText()+"')");
                db.insert("INSERT INTO STOIXEIA(ID,ARITHMOSTAUTOTITAS,IMEROMINIAEISODOU,IMEROMINIAEKSODOU,EIDIKOTITA) VALUES("+currentID+",'"+artautoText.getText()+"','"+imEisText.getText()+"','"+imeks.getText()+"','"+eidikotitaText.getText()+"')");            

                setTableData();
                clearText();
                JOptionPane.showMessageDialog(null, "Η εισαγωγή ολοκληρώθηκε", "",
                                       JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Υπήρξε πρόβλημα κατά την εισαγωγή", "Error",
                                        JOptionPane.ERROR_MESSAGE);
            }
        }else{
             JOptionPane.showMessageDialog(null, "Υπήρξε πρόβλημα κατά την εισαγωγή", "Error",
                                        JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_insertBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
        
        if(idExists(id)){
            if(roomText.getText().matches("[0-9]*")){
                db.insert("UPDATE STUDENT SET SNAME = '"+nameText.getText()+"', SLASTNAME = '"+surnameText.getText()+"', SROOM = '"+roomText.getText()+"' WHERE ID = " + id );
                db.insert("UPDATE ADDRESS SET NOMOS = '"+stateText.getText()+"', POLI = '"+cityText.getText()+"', DIEUTHINSI = '" + addressText.getText() + "', ARITHMOS = " + Integer.valueOf(numberText.getText()) + " WHERE ID = " + id );
                db.insert("UPDATE GONEIS SET ONOMAMITROS = '"+mothernameText.getText()+"', ONOMAPATROS = '"+fathernameText.getText()+ "' WHERE ID = " + id );
                db.insert("UPDATE TILEFONO SET KINITOIDIOU = '"+kinitoText.getText()+"', KINITOPATROS = '"+kinitopText.getText()+"', KINITOMITROS = '" + kinitomText.getText() + "', STATHERO = '" + statheroText.getText() + "' WHERE ID = " + id );
                db.insert("UPDATE STOIXEIA SET ARITHMOSTAUTOTITAS = '"+artautoText.getText()+"', IMEROMINIAEISODOU = '"+imEisText.getText()+"', IMEROMINIAEKSODOU = '"+imeks.getText()+"', EIDIKOTITA = '" + eidikotitaText.getText() + "' WHERE ID = " + id );
                setTableData();
                clearText();
                JOptionPane.showMessageDialog(null, "Η εγγραφή ανανεώθηκε με επιτυχία!", "",
                                    JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Room field should be a number", "Error",
                                    JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "ID does not match or User did not input a number", "Error",
                                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateBtnActionPerformed
    private void clearText(){
        nameText.setText("");
        surnameText.setText("");
        roomText.setText("");
        stateText.setText("");
        cityText.setText("");
        addressText.setText("");
        numberText.setText("");
        fathernameText.setText("");
        mothernameText.setText("");
        kinitoText.setText("");
        kinitomText.setText("");
        kinitopText.setText("");
        statheroText.setText("");
        artautoText.setText("");
        imEisText.setText("");
        imeks.setText("");
        eidikotitaText.setText("");
        
    }
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        
        if(idExists(id)){
           int selectedOption = JOptionPane.showOptionDialog(null, 
                    "Είστε βέβαιοι πως θέλετε να διαγράψετε τα στοιχεία του φοιτητή?", 
                    "Επιλογή", 
                    JOptionPane.OK_CANCEL_OPTION, 
                    JOptionPane.INFORMATION_MESSAGE, 
                    null, 
                    new String[]{"Ναι", "Όχι"}, // this is the array
                    "default");
            if(selectedOption == JOptionPane.YES_OPTION){
                DBController olddb = new DBController("ESTIA_OLD", "");
                olddb.insert("INSERT INTO OLD_STUDENTS"+
                        "(SNAME,SURNAME,ROOM,STATE,CITY,STREET,NUMBER,"+
                        "MNAME,FNAME,PHONE,MPHONE,FPHONE,SPHONE,AS_TAU,IM_EIS,IM_EKS,EIDIKOTITA) VALUES('" +
                        nameText.getText() + 
                        "','" + surnameText.getText() + "'," + Integer.parseInt(roomText.getText()) + 
                        ",'" + stateText.getText() + "','" + cityText.getText() + "','" + 
                        addressText.getText() + "'," + Integer.parseInt(numberText.getText()) + ",'" 
                        + mothernameText.getText() + "','" + fathernameText.getText() + "','" + 
                        kinitoText.getText() + "','" + kinitomText.getText() + "','" + 
                        kinitopText.getText() + "','" + statheroText.getText() + "','" + 
                        artautoText.getText() + "','" + imEisText.getText() + "','" + 
                        imeks.getText() + "','" + eidikotitaText.getText() + "')");
                db.insert("DELETE FROM STUDENT WHERE ID = " + id );
                db.insert("DELETE FROM ADDRESS WHERE ID = " + id );
                db.insert("DELETE FROM GONEIS WHERE ID = " + id );
                db.insert("DELETE FROM TILEFONO WHERE ID = " + id );
                db.insert("DELETE FROM STOIXEIA WHERE ID = " + id );
                JOptionPane.showMessageDialog(null, "Τα στοιχεία του φοιτητή διαγράφηκαν με επιτυχία", "",
                                    JOptionPane.INFORMATION_MESSAGE);
            }

            setTableData();
            id = 0;
            
            clearText();
            
            
        }else{
            JOptionPane.showMessageDialog(null, "ID does not match or User did not input a number", "Error",
                                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed

        try {
            jTable1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(UserPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed
    
    
    
    private boolean idExists(int id){
        TableModel model = jTable1.getModel();
        if(String.valueOf(id).matches("[0-9]*"))
            for(int i = 0; i < model.getRowCount(); i++){
                if(String.valueOf(id).equals(model.getValueAt(i, 0)));
                    return true;
            }
        return false;
    }
    private int id;
    private int currentID;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField artautoText;
    private javax.swing.JTextField cityText;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField eidikotitaText;
    private javax.swing.JTextField fathernameText;
    private javax.swing.JTextField imEisText;
    private javax.swing.JTextField imeks;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kinitoText;
    private javax.swing.JTextField kinitomText;
    private javax.swing.JTextField kinitopText;
    private javax.swing.JTextField mothernameText;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField numberText;
    private javax.swing.JButton printButton;
    private javax.swing.JTextField roomText;
    private javax.swing.JTextField stateText;
    private javax.swing.JTextField statheroText;
    private javax.swing.JTextField surnameText;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
